name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        extras:
          - ''
          - '[speedups]'
          - '[speedups,rasterio]'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade Python bits
      run: |
        python -m pip install --upgrade pip coverage wheel setuptools
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Install development files
      if: matrix.python-version == '3.9'
      run: |
        sudo apt-get install -y fftw3-dev
        python -m pip install Cython
    - name: Install app
      run: python -m pip install -e ."$EXTRAS"
      env:
        EXTRAS: '${{ matrix.extras }}'
    - name: Run tests with coverage
      run: coverage run --source=image_similarity_metrics -m pytest -v tests && coverage report -m
    - name: Report coverage
      continue-on-error: true
      run: coverage report
